// Generated by gencpp from file jetson/Sendselect.msg
// DO NOT EDIT!


#ifndef JETSON_MESSAGE_SENDSELECT_H
#define JETSON_MESSAGE_SENDSELECT_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace jetson
{
template <class ContainerAllocator>
struct Sendselect_
{
  typedef Sendselect_<ContainerAllocator> Type;

  Sendselect_()
    : p1()
    , p2()
    , p3()
    , p4()  {
    }
  Sendselect_(const ContainerAllocator& _alloc)
    : p1(_alloc)
    , p2(_alloc)
    , p3(_alloc)
    , p4(_alloc)  {
  (void)_alloc;
    }



   typedef std::vector<int32_t, typename ContainerAllocator::template rebind<int32_t>::other >  _p1_type;
  _p1_type p1;

   typedef std::vector<int32_t, typename ContainerAllocator::template rebind<int32_t>::other >  _p2_type;
  _p2_type p2;

   typedef std::vector<int32_t, typename ContainerAllocator::template rebind<int32_t>::other >  _p3_type;
  _p3_type p3;

   typedef std::vector<int32_t, typename ContainerAllocator::template rebind<int32_t>::other >  _p4_type;
  _p4_type p4;




  typedef boost::shared_ptr< ::jetson::Sendselect_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::jetson::Sendselect_<ContainerAllocator> const> ConstPtr;

}; // struct Sendselect_

typedef ::jetson::Sendselect_<std::allocator<void> > Sendselect;

typedef boost::shared_ptr< ::jetson::Sendselect > SendselectPtr;
typedef boost::shared_ptr< ::jetson::Sendselect const> SendselectConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::jetson::Sendselect_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::jetson::Sendselect_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace jetson

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'jetson': ['/home/ubuntu/hj/workspace/jetson-ros/src/jetson/msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::jetson::Sendselect_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::jetson::Sendselect_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::jetson::Sendselect_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::jetson::Sendselect_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::jetson::Sendselect_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::jetson::Sendselect_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::jetson::Sendselect_<ContainerAllocator> >
{
  static const char* value()
  {
    return "8b5268e6173b27a274f80ce71e47b82b";
  }

  static const char* value(const ::jetson::Sendselect_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x8b5268e6173b27a2ULL;
  static const uint64_t static_value2 = 0x74f80ce71e47b82bULL;
};

template<class ContainerAllocator>
struct DataType< ::jetson::Sendselect_<ContainerAllocator> >
{
  static const char* value()
  {
    return "jetson/Sendselect";
  }

  static const char* value(const ::jetson::Sendselect_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::jetson::Sendselect_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int32[] p1\n\
int32[] p2\n\
int32[] p3\n\
int32[] p4\n\
";
  }

  static const char* value(const ::jetson::Sendselect_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::jetson::Sendselect_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.p1);
      stream.next(m.p2);
      stream.next(m.p3);
      stream.next(m.p4);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Sendselect_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::jetson::Sendselect_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::jetson::Sendselect_<ContainerAllocator>& v)
  {
    s << indent << "p1[]" << std::endl;
    for (size_t i = 0; i < v.p1.size(); ++i)
    {
      s << indent << "  p1[" << i << "]: ";
      Printer<int32_t>::stream(s, indent + "  ", v.p1[i]);
    }
    s << indent << "p2[]" << std::endl;
    for (size_t i = 0; i < v.p2.size(); ++i)
    {
      s << indent << "  p2[" << i << "]: ";
      Printer<int32_t>::stream(s, indent + "  ", v.p2[i]);
    }
    s << indent << "p3[]" << std::endl;
    for (size_t i = 0; i < v.p3.size(); ++i)
    {
      s << indent << "  p3[" << i << "]: ";
      Printer<int32_t>::stream(s, indent + "  ", v.p3[i]);
    }
    s << indent << "p4[]" << std::endl;
    for (size_t i = 0; i < v.p4.size(); ++i)
    {
      s << indent << "  p4[" << i << "]: ";
      Printer<int32_t>::stream(s, indent + "  ", v.p4[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // JETSON_MESSAGE_SENDSELECT_H
