# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from dji_sdk/FlightControlInfo.msg. Do not edit."""
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct


class FlightControlInfo(genpy.Message):
  _md5sum = "943648dc47db23e3c3071c5427b1db2b"
  _type = "dji_sdk/FlightControlInfo"
  _has_header = False #flag to mark the presence of a Header object
  _full_text = """#control mode
uint8 control_mode
#0:rc, 1:mobile, 2:onboard
uint8 cur_ctrl_dev_in_navi_mode
#0:disabled, 1:enabled
uint8 serial_req_status
#0:disabled, 1:enabled
uint8 virtual_rc_status
"""
  __slots__ = ['control_mode','cur_ctrl_dev_in_navi_mode','serial_req_status','virtual_rc_status']
  _slot_types = ['uint8','uint8','uint8','uint8']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       control_mode,cur_ctrl_dev_in_navi_mode,serial_req_status,virtual_rc_status

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(FlightControlInfo, self).__init__(*args, **kwds)
      #message fields cannot be None, assign default values for those that are
      if self.control_mode is None:
        self.control_mode = 0
      if self.cur_ctrl_dev_in_navi_mode is None:
        self.cur_ctrl_dev_in_navi_mode = 0
      if self.serial_req_status is None:
        self.serial_req_status = 0
      if self.virtual_rc_status is None:
        self.virtual_rc_status = 0
    else:
      self.control_mode = 0
      self.cur_ctrl_dev_in_navi_mode = 0
      self.serial_req_status = 0
      self.virtual_rc_status = 0

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_struct_4B.pack(_x.control_mode, _x.cur_ctrl_dev_in_navi_mode, _x.serial_req_status, _x.virtual_rc_status))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    try:
      end = 0
      _x = self
      start = end
      end += 4
      (_x.control_mode, _x.cur_ctrl_dev_in_navi_mode, _x.serial_req_status, _x.virtual_rc_status,) = _struct_4B.unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_struct_4B.pack(_x.control_mode, _x.cur_ctrl_dev_in_navi_mode, _x.serial_req_status, _x.virtual_rc_status))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    try:
      end = 0
      _x = self
      start = end
      end += 4
      (_x.control_mode, _x.cur_ctrl_dev_in_navi_mode, _x.serial_req_status, _x.virtual_rc_status,) = _struct_4B.unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill

_struct_I = genpy.struct_I
_struct_4B = struct.Struct("<4B")
