# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from dji_sdk/MissionFollowmeTask.msg. Do not edit."""
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct


class MissionFollowmeTask(genpy.Message):
  _md5sum = "0b5547386d29daca9e6c32595ec4ca50"
  _type = "dji_sdk/MissionFollowmeTask"
  _has_header = False #flag to mark the presence of a Header object
  _full_text = """uint8 mode
uint8 yaw_mode
float64 initial_latitude
float64 initial_longitude
uint16 initial_altitude
uint8 sensitivity
"""
  __slots__ = ['mode','yaw_mode','initial_latitude','initial_longitude','initial_altitude','sensitivity']
  _slot_types = ['uint8','uint8','float64','float64','uint16','uint8']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       mode,yaw_mode,initial_latitude,initial_longitude,initial_altitude,sensitivity

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(MissionFollowmeTask, self).__init__(*args, **kwds)
      #message fields cannot be None, assign default values for those that are
      if self.mode is None:
        self.mode = 0
      if self.yaw_mode is None:
        self.yaw_mode = 0
      if self.initial_latitude is None:
        self.initial_latitude = 0.
      if self.initial_longitude is None:
        self.initial_longitude = 0.
      if self.initial_altitude is None:
        self.initial_altitude = 0
      if self.sensitivity is None:
        self.sensitivity = 0
    else:
      self.mode = 0
      self.yaw_mode = 0
      self.initial_latitude = 0.
      self.initial_longitude = 0.
      self.initial_altitude = 0
      self.sensitivity = 0

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_struct_2B2dHB.pack(_x.mode, _x.yaw_mode, _x.initial_latitude, _x.initial_longitude, _x.initial_altitude, _x.sensitivity))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    try:
      end = 0
      _x = self
      start = end
      end += 21
      (_x.mode, _x.yaw_mode, _x.initial_latitude, _x.initial_longitude, _x.initial_altitude, _x.sensitivity,) = _struct_2B2dHB.unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_struct_2B2dHB.pack(_x.mode, _x.yaw_mode, _x.initial_latitude, _x.initial_longitude, _x.initial_altitude, _x.sensitivity))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    try:
      end = 0
      _x = self
      start = end
      end += 21
      (_x.mode, _x.yaw_mode, _x.initial_latitude, _x.initial_longitude, _x.initial_altitude, _x.sensitivity,) = _struct_2B2dHB.unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill

_struct_I = genpy.struct_I
_struct_2B2dHB = struct.Struct("<2B2dHB")
