# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from dji_sdk/MissionStatusOther.msg. Do not edit."""
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct


class MissionStatusOther(genpy.Message):
  _md5sum = "a0261ae1eb980895a8685db930ec1a68"
  _type = "dji_sdk/MissionStatusOther"
  _has_header = False #flag to mark the presence of a Header object
  _full_text = """uint8 mission_type
uint8 last_mission_type
uint8 is_broken
uint8 error_code
"""
  __slots__ = ['mission_type','last_mission_type','is_broken','error_code']
  _slot_types = ['uint8','uint8','uint8','uint8']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       mission_type,last_mission_type,is_broken,error_code

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(MissionStatusOther, self).__init__(*args, **kwds)
      #message fields cannot be None, assign default values for those that are
      if self.mission_type is None:
        self.mission_type = 0
      if self.last_mission_type is None:
        self.last_mission_type = 0
      if self.is_broken is None:
        self.is_broken = 0
      if self.error_code is None:
        self.error_code = 0
    else:
      self.mission_type = 0
      self.last_mission_type = 0
      self.is_broken = 0
      self.error_code = 0

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_struct_4B.pack(_x.mission_type, _x.last_mission_type, _x.is_broken, _x.error_code))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    try:
      end = 0
      _x = self
      start = end
      end += 4
      (_x.mission_type, _x.last_mission_type, _x.is_broken, _x.error_code,) = _struct_4B.unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_struct_4B.pack(_x.mission_type, _x.last_mission_type, _x.is_broken, _x.error_code))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    try:
      end = 0
      _x = self
      start = end
      end += 4
      (_x.mission_type, _x.last_mission_type, _x.is_broken, _x.error_code,) = _struct_4B.unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill

_struct_I = genpy.struct_I
_struct_4B = struct.Struct("<4B")
