# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from dji_sdk/MissionHotpointTask.msg. Do not edit."""
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct


class MissionHotpointTask(genpy.Message):
  _md5sum = "5700988132c5f205ad38c15800896e84"
  _type = "dji_sdk/MissionHotpointTask"
  _has_header = False #flag to mark the presence of a Header object
  _full_text = """float64 latitude
float64 longitude
float64 altitude
float64 radius
float32 angular_speed
uint8 is_clockwise
uint8 start_point
uint8 yaw_mode
"""
  __slots__ = ['latitude','longitude','altitude','radius','angular_speed','is_clockwise','start_point','yaw_mode']
  _slot_types = ['float64','float64','float64','float64','float32','uint8','uint8','uint8']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       latitude,longitude,altitude,radius,angular_speed,is_clockwise,start_point,yaw_mode

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(MissionHotpointTask, self).__init__(*args, **kwds)
      #message fields cannot be None, assign default values for those that are
      if self.latitude is None:
        self.latitude = 0.
      if self.longitude is None:
        self.longitude = 0.
      if self.altitude is None:
        self.altitude = 0.
      if self.radius is None:
        self.radius = 0.
      if self.angular_speed is None:
        self.angular_speed = 0.
      if self.is_clockwise is None:
        self.is_clockwise = 0
      if self.start_point is None:
        self.start_point = 0
      if self.yaw_mode is None:
        self.yaw_mode = 0
    else:
      self.latitude = 0.
      self.longitude = 0.
      self.altitude = 0.
      self.radius = 0.
      self.angular_speed = 0.
      self.is_clockwise = 0
      self.start_point = 0
      self.yaw_mode = 0

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_struct_4df3B.pack(_x.latitude, _x.longitude, _x.altitude, _x.radius, _x.angular_speed, _x.is_clockwise, _x.start_point, _x.yaw_mode))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    try:
      end = 0
      _x = self
      start = end
      end += 39
      (_x.latitude, _x.longitude, _x.altitude, _x.radius, _x.angular_speed, _x.is_clockwise, _x.start_point, _x.yaw_mode,) = _struct_4df3B.unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_struct_4df3B.pack(_x.latitude, _x.longitude, _x.altitude, _x.radius, _x.angular_speed, _x.is_clockwise, _x.start_point, _x.yaw_mode))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    try:
      end = 0
      _x = self
      start = end
      end += 39
      (_x.latitude, _x.longitude, _x.altitude, _x.radius, _x.angular_speed, _x.is_clockwise, _x.start_point, _x.yaw_mode,) = _struct_4df3B.unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill

_struct_I = genpy.struct_I
_struct_4df3B = struct.Struct("<4df3B")
