// Generated by gencpp from file kcf_detect/dectrect.msg
// DO NOT EDIT!


#ifndef KCF_DETECT_MESSAGE_DECTRECT_H
#define KCF_DETECT_MESSAGE_DECTRECT_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace kcf_detect
{
template <class ContainerAllocator>
struct dectrect_
{
  typedef dectrect_<ContainerAllocator> Type;

  dectrect_()
    : x()
    , y()
    , w()
    , h()  {
    }
  dectrect_(const ContainerAllocator& _alloc)
    : x(_alloc)
    , y(_alloc)
    , w(_alloc)
    , h(_alloc)  {
  (void)_alloc;
    }



   typedef std::vector<int32_t, typename ContainerAllocator::template rebind<int32_t>::other >  _x_type;
  _x_type x;

   typedef std::vector<int32_t, typename ContainerAllocator::template rebind<int32_t>::other >  _y_type;
  _y_type y;

   typedef std::vector<int32_t, typename ContainerAllocator::template rebind<int32_t>::other >  _w_type;
  _w_type w;

   typedef std::vector<int32_t, typename ContainerAllocator::template rebind<int32_t>::other >  _h_type;
  _h_type h;




  typedef boost::shared_ptr< ::kcf_detect::dectrect_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::kcf_detect::dectrect_<ContainerAllocator> const> ConstPtr;

}; // struct dectrect_

typedef ::kcf_detect::dectrect_<std::allocator<void> > dectrect;

typedef boost::shared_ptr< ::kcf_detect::dectrect > dectrectPtr;
typedef boost::shared_ptr< ::kcf_detect::dectrect const> dectrectConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::kcf_detect::dectrect_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::kcf_detect::dectrect_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace kcf_detect

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/indigo/share/std_msgs/cmake/../msg'], 'kcf_detect': ['/home/ubuntu/cc/rosdji_sdk/src/Onboard-SDK-ROS-3.1/kcf_detect/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::kcf_detect::dectrect_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::kcf_detect::dectrect_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::kcf_detect::dectrect_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::kcf_detect::dectrect_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::kcf_detect::dectrect_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::kcf_detect::dectrect_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::kcf_detect::dectrect_<ContainerAllocator> >
{
  static const char* value()
  {
    return "13860a6b7a8df7b796f4eac3c5475ca0";
  }

  static const char* value(const ::kcf_detect::dectrect_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x13860a6b7a8df7b7ULL;
  static const uint64_t static_value2 = 0x96f4eac3c5475ca0ULL;
};

template<class ContainerAllocator>
struct DataType< ::kcf_detect::dectrect_<ContainerAllocator> >
{
  static const char* value()
  {
    return "kcf_detect/dectrect";
  }

  static const char* value(const ::kcf_detect::dectrect_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::kcf_detect::dectrect_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int32[] x\n\
int32[] y\n\
int32[] w\n\
int32[] h\n\
";
  }

  static const char* value(const ::kcf_detect::dectrect_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::kcf_detect::dectrect_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.x);
      stream.next(m.y);
      stream.next(m.w);
      stream.next(m.h);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct dectrect_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::kcf_detect::dectrect_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::kcf_detect::dectrect_<ContainerAllocator>& v)
  {
    s << indent << "x[]" << std::endl;
    for (size_t i = 0; i < v.x.size(); ++i)
    {
      s << indent << "  x[" << i << "]: ";
      Printer<int32_t>::stream(s, indent + "  ", v.x[i]);
    }
    s << indent << "y[]" << std::endl;
    for (size_t i = 0; i < v.y.size(); ++i)
    {
      s << indent << "  y[" << i << "]: ";
      Printer<int32_t>::stream(s, indent + "  ", v.y[i]);
    }
    s << indent << "w[]" << std::endl;
    for (size_t i = 0; i < v.w.size(); ++i)
    {
      s << indent << "  w[" << i << "]: ";
      Printer<int32_t>::stream(s, indent + "  ", v.w[i]);
    }
    s << indent << "h[]" << std::endl;
    for (size_t i = 0; i < v.h.size(); ++i)
    {
      s << indent << "  h[" << i << "]: ";
      Printer<int32_t>::stream(s, indent + "  ", v.h[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // KCF_DETECT_MESSAGE_DECTRECT_H
