// Generated by gencpp from file dji_sdk/FlightControlInfo.msg
// DO NOT EDIT!


#ifndef DJI_SDK_MESSAGE_FLIGHTCONTROLINFO_H
#define DJI_SDK_MESSAGE_FLIGHTCONTROLINFO_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace dji_sdk
{
template <class ContainerAllocator>
struct FlightControlInfo_
{
  typedef FlightControlInfo_<ContainerAllocator> Type;

  FlightControlInfo_()
    : control_mode(0)
    , cur_ctrl_dev_in_navi_mode(0)
    , serial_req_status(0)
    , virtual_rc_status(0)  {
    }
  FlightControlInfo_(const ContainerAllocator& _alloc)
    : control_mode(0)
    , cur_ctrl_dev_in_navi_mode(0)
    , serial_req_status(0)
    , virtual_rc_status(0)  {
  (void)_alloc;
    }



   typedef uint8_t _control_mode_type;
  _control_mode_type control_mode;

   typedef uint8_t _cur_ctrl_dev_in_navi_mode_type;
  _cur_ctrl_dev_in_navi_mode_type cur_ctrl_dev_in_navi_mode;

   typedef uint8_t _serial_req_status_type;
  _serial_req_status_type serial_req_status;

   typedef uint8_t _virtual_rc_status_type;
  _virtual_rc_status_type virtual_rc_status;




  typedef boost::shared_ptr< ::dji_sdk::FlightControlInfo_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::dji_sdk::FlightControlInfo_<ContainerAllocator> const> ConstPtr;

}; // struct FlightControlInfo_

typedef ::dji_sdk::FlightControlInfo_<std::allocator<void> > FlightControlInfo;

typedef boost::shared_ptr< ::dji_sdk::FlightControlInfo > FlightControlInfoPtr;
typedef boost::shared_ptr< ::dji_sdk::FlightControlInfo const> FlightControlInfoConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::dji_sdk::FlightControlInfo_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::dji_sdk::FlightControlInfo_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace dji_sdk

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'nav_msgs': ['/opt/ros/indigo/share/nav_msgs/cmake/../msg'], 'dji_sdk': ['/home/ubuntu/cc/rosdji_sdk/src/Onboard-SDK-ROS-3.1/dji_sdk/msg', '/home/ubuntu/cc/rosdji_sdk/devel/share/dji_sdk/msg'], 'actionlib_msgs': ['/opt/ros/indigo/share/actionlib_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/indigo/share/geometry_msgs/cmake/../msg'], 'std_msgs': ['/opt/ros/indigo/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::dji_sdk::FlightControlInfo_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::dji_sdk::FlightControlInfo_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::dji_sdk::FlightControlInfo_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::dji_sdk::FlightControlInfo_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::dji_sdk::FlightControlInfo_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::dji_sdk::FlightControlInfo_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::dji_sdk::FlightControlInfo_<ContainerAllocator> >
{
  static const char* value()
  {
    return "943648dc47db23e3c3071c5427b1db2b";
  }

  static const char* value(const ::dji_sdk::FlightControlInfo_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x943648dc47db23e3ULL;
  static const uint64_t static_value2 = 0xc3071c5427b1db2bULL;
};

template<class ContainerAllocator>
struct DataType< ::dji_sdk::FlightControlInfo_<ContainerAllocator> >
{
  static const char* value()
  {
    return "dji_sdk/FlightControlInfo";
  }

  static const char* value(const ::dji_sdk::FlightControlInfo_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::dji_sdk::FlightControlInfo_<ContainerAllocator> >
{
  static const char* value()
  {
    return "#control mode\n\
uint8 control_mode\n\
#0:rc, 1:mobile, 2:onboard\n\
uint8 cur_ctrl_dev_in_navi_mode\n\
#0:disabled, 1:enabled\n\
uint8 serial_req_status\n\
#0:disabled, 1:enabled\n\
uint8 virtual_rc_status\n\
";
  }

  static const char* value(const ::dji_sdk::FlightControlInfo_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::dji_sdk::FlightControlInfo_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.control_mode);
      stream.next(m.cur_ctrl_dev_in_navi_mode);
      stream.next(m.serial_req_status);
      stream.next(m.virtual_rc_status);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct FlightControlInfo_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::dji_sdk::FlightControlInfo_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::dji_sdk::FlightControlInfo_<ContainerAllocator>& v)
  {
    s << indent << "control_mode: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.control_mode);
    s << indent << "cur_ctrl_dev_in_navi_mode: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.cur_ctrl_dev_in_navi_mode);
    s << indent << "serial_req_status: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.serial_req_status);
    s << indent << "virtual_rc_status: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.virtual_rc_status);
  }
};

} // namespace message_operations
} // namespace ros

#endif // DJI_SDK_MESSAGE_FLIGHTCONTROLINFO_H
