// Generated by gencpp from file dji_sdk/GimbalSpeedControl.msg
// DO NOT EDIT!


#ifndef DJI_SDK_MESSAGE_GIMBALSPEEDCONTROL_H
#define DJI_SDK_MESSAGE_GIMBALSPEEDCONTROL_H

#include <ros/service_traits.h>


#include <dji_sdk/GimbalSpeedControlRequest.h>
#include <dji_sdk/GimbalSpeedControlResponse.h>


namespace dji_sdk
{

struct GimbalSpeedControl
{

typedef GimbalSpeedControlRequest Request;
typedef GimbalSpeedControlResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct GimbalSpeedControl
} // namespace dji_sdk


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::dji_sdk::GimbalSpeedControl > {
  static const char* value()
  {
    return "9faf8f80ceb051ef1bc0985e17a03fa5";
  }

  static const char* value(const ::dji_sdk::GimbalSpeedControl&) { return value(); }
};

template<>
struct DataType< ::dji_sdk::GimbalSpeedControl > {
  static const char* value()
  {
    return "dji_sdk/GimbalSpeedControl";
  }

  static const char* value(const ::dji_sdk::GimbalSpeedControl&) { return value(); }
};


// service_traits::MD5Sum< ::dji_sdk::GimbalSpeedControlRequest> should match 
// service_traits::MD5Sum< ::dji_sdk::GimbalSpeedControl > 
template<>
struct MD5Sum< ::dji_sdk::GimbalSpeedControlRequest>
{
  static const char* value()
  {
    return MD5Sum< ::dji_sdk::GimbalSpeedControl >::value();
  }
  static const char* value(const ::dji_sdk::GimbalSpeedControlRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::dji_sdk::GimbalSpeedControlRequest> should match 
// service_traits::DataType< ::dji_sdk::GimbalSpeedControl > 
template<>
struct DataType< ::dji_sdk::GimbalSpeedControlRequest>
{
  static const char* value()
  {
    return DataType< ::dji_sdk::GimbalSpeedControl >::value();
  }
  static const char* value(const ::dji_sdk::GimbalSpeedControlRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::dji_sdk::GimbalSpeedControlResponse> should match 
// service_traits::MD5Sum< ::dji_sdk::GimbalSpeedControl > 
template<>
struct MD5Sum< ::dji_sdk::GimbalSpeedControlResponse>
{
  static const char* value()
  {
    return MD5Sum< ::dji_sdk::GimbalSpeedControl >::value();
  }
  static const char* value(const ::dji_sdk::GimbalSpeedControlResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::dji_sdk::GimbalSpeedControlResponse> should match 
// service_traits::DataType< ::dji_sdk::GimbalSpeedControl > 
template<>
struct DataType< ::dji_sdk::GimbalSpeedControlResponse>
{
  static const char* value()
  {
    return DataType< ::dji_sdk::GimbalSpeedControl >::value();
  }
  static const char* value(const ::dji_sdk::GimbalSpeedControlResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // DJI_SDK_MESSAGE_GIMBALSPEEDCONTROL_H
