// Generated by gencpp from file dji_sdk/GimbalAngleControl.msg
// DO NOT EDIT!


#ifndef DJI_SDK_MESSAGE_GIMBALANGLECONTROL_H
#define DJI_SDK_MESSAGE_GIMBALANGLECONTROL_H

#include <ros/service_traits.h>


#include <dji_sdk/GimbalAngleControlRequest.h>
#include <dji_sdk/GimbalAngleControlResponse.h>


namespace dji_sdk
{

struct GimbalAngleControl
{

typedef GimbalAngleControlRequest Request;
typedef GimbalAngleControlResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct GimbalAngleControl
} // namespace dji_sdk


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::dji_sdk::GimbalAngleControl > {
  static const char* value()
  {
    return "355893b815576f75c0061dddd133c146";
  }

  static const char* value(const ::dji_sdk::GimbalAngleControl&) { return value(); }
};

template<>
struct DataType< ::dji_sdk::GimbalAngleControl > {
  static const char* value()
  {
    return "dji_sdk/GimbalAngleControl";
  }

  static const char* value(const ::dji_sdk::GimbalAngleControl&) { return value(); }
};


// service_traits::MD5Sum< ::dji_sdk::GimbalAngleControlRequest> should match 
// service_traits::MD5Sum< ::dji_sdk::GimbalAngleControl > 
template<>
struct MD5Sum< ::dji_sdk::GimbalAngleControlRequest>
{
  static const char* value()
  {
    return MD5Sum< ::dji_sdk::GimbalAngleControl >::value();
  }
  static const char* value(const ::dji_sdk::GimbalAngleControlRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::dji_sdk::GimbalAngleControlRequest> should match 
// service_traits::DataType< ::dji_sdk::GimbalAngleControl > 
template<>
struct DataType< ::dji_sdk::GimbalAngleControlRequest>
{
  static const char* value()
  {
    return DataType< ::dji_sdk::GimbalAngleControl >::value();
  }
  static const char* value(const ::dji_sdk::GimbalAngleControlRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::dji_sdk::GimbalAngleControlResponse> should match 
// service_traits::MD5Sum< ::dji_sdk::GimbalAngleControl > 
template<>
struct MD5Sum< ::dji_sdk::GimbalAngleControlResponse>
{
  static const char* value()
  {
    return MD5Sum< ::dji_sdk::GimbalAngleControl >::value();
  }
  static const char* value(const ::dji_sdk::GimbalAngleControlResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::dji_sdk::GimbalAngleControlResponse> should match 
// service_traits::DataType< ::dji_sdk::GimbalAngleControl > 
template<>
struct DataType< ::dji_sdk::GimbalAngleControlResponse>
{
  static const char* value()
  {
    return DataType< ::dji_sdk::GimbalAngleControl >::value();
  }
  static const char* value(const ::dji_sdk::GimbalAngleControlResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // DJI_SDK_MESSAGE_GIMBALANGLECONTROL_H
