// Generated by gencpp from file dji_sdk/GlobalPositionControl.msg
// DO NOT EDIT!


#ifndef DJI_SDK_MESSAGE_GLOBALPOSITIONCONTROL_H
#define DJI_SDK_MESSAGE_GLOBALPOSITIONCONTROL_H

#include <ros/service_traits.h>


#include <dji_sdk/GlobalPositionControlRequest.h>
#include <dji_sdk/GlobalPositionControlResponse.h>


namespace dji_sdk
{

struct GlobalPositionControl
{

typedef GlobalPositionControlRequest Request;
typedef GlobalPositionControlResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct GlobalPositionControl
} // namespace dji_sdk


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::dji_sdk::GlobalPositionControl > {
  static const char* value()
  {
    return "760463c3d8356eaf13428439b7b2ac10";
  }

  static const char* value(const ::dji_sdk::GlobalPositionControl&) { return value(); }
};

template<>
struct DataType< ::dji_sdk::GlobalPositionControl > {
  static const char* value()
  {
    return "dji_sdk/GlobalPositionControl";
  }

  static const char* value(const ::dji_sdk::GlobalPositionControl&) { return value(); }
};


// service_traits::MD5Sum< ::dji_sdk::GlobalPositionControlRequest> should match 
// service_traits::MD5Sum< ::dji_sdk::GlobalPositionControl > 
template<>
struct MD5Sum< ::dji_sdk::GlobalPositionControlRequest>
{
  static const char* value()
  {
    return MD5Sum< ::dji_sdk::GlobalPositionControl >::value();
  }
  static const char* value(const ::dji_sdk::GlobalPositionControlRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::dji_sdk::GlobalPositionControlRequest> should match 
// service_traits::DataType< ::dji_sdk::GlobalPositionControl > 
template<>
struct DataType< ::dji_sdk::GlobalPositionControlRequest>
{
  static const char* value()
  {
    return DataType< ::dji_sdk::GlobalPositionControl >::value();
  }
  static const char* value(const ::dji_sdk::GlobalPositionControlRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::dji_sdk::GlobalPositionControlResponse> should match 
// service_traits::MD5Sum< ::dji_sdk::GlobalPositionControl > 
template<>
struct MD5Sum< ::dji_sdk::GlobalPositionControlResponse>
{
  static const char* value()
  {
    return MD5Sum< ::dji_sdk::GlobalPositionControl >::value();
  }
  static const char* value(const ::dji_sdk::GlobalPositionControlResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::dji_sdk::GlobalPositionControlResponse> should match 
// service_traits::DataType< ::dji_sdk::GlobalPositionControl > 
template<>
struct DataType< ::dji_sdk::GlobalPositionControlResponse>
{
  static const char* value()
  {
    return DataType< ::dji_sdk::GlobalPositionControl >::value();
  }
  static const char* value(const ::dji_sdk::GlobalPositionControlResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // DJI_SDK_MESSAGE_GLOBALPOSITIONCONTROL_H
