// Generated by gencpp from file dji_sdk/LocalPositionControl.msg
// DO NOT EDIT!


#ifndef DJI_SDK_MESSAGE_LOCALPOSITIONCONTROL_H
#define DJI_SDK_MESSAGE_LOCALPOSITIONCONTROL_H

#include <ros/service_traits.h>


#include <dji_sdk/LocalPositionControlRequest.h>
#include <dji_sdk/LocalPositionControlResponse.h>


namespace dji_sdk
{

struct LocalPositionControl
{

typedef LocalPositionControlRequest Request;
typedef LocalPositionControlResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct LocalPositionControl
} // namespace dji_sdk


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::dji_sdk::LocalPositionControl > {
  static const char* value()
  {
    return "af2171d66d09e82c491cb7139793b007";
  }

  static const char* value(const ::dji_sdk::LocalPositionControl&) { return value(); }
};

template<>
struct DataType< ::dji_sdk::LocalPositionControl > {
  static const char* value()
  {
    return "dji_sdk/LocalPositionControl";
  }

  static const char* value(const ::dji_sdk::LocalPositionControl&) { return value(); }
};


// service_traits::MD5Sum< ::dji_sdk::LocalPositionControlRequest> should match 
// service_traits::MD5Sum< ::dji_sdk::LocalPositionControl > 
template<>
struct MD5Sum< ::dji_sdk::LocalPositionControlRequest>
{
  static const char* value()
  {
    return MD5Sum< ::dji_sdk::LocalPositionControl >::value();
  }
  static const char* value(const ::dji_sdk::LocalPositionControlRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::dji_sdk::LocalPositionControlRequest> should match 
// service_traits::DataType< ::dji_sdk::LocalPositionControl > 
template<>
struct DataType< ::dji_sdk::LocalPositionControlRequest>
{
  static const char* value()
  {
    return DataType< ::dji_sdk::LocalPositionControl >::value();
  }
  static const char* value(const ::dji_sdk::LocalPositionControlRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::dji_sdk::LocalPositionControlResponse> should match 
// service_traits::MD5Sum< ::dji_sdk::LocalPositionControl > 
template<>
struct MD5Sum< ::dji_sdk::LocalPositionControlResponse>
{
  static const char* value()
  {
    return MD5Sum< ::dji_sdk::LocalPositionControl >::value();
  }
  static const char* value(const ::dji_sdk::LocalPositionControlResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::dji_sdk::LocalPositionControlResponse> should match 
// service_traits::DataType< ::dji_sdk::LocalPositionControl > 
template<>
struct DataType< ::dji_sdk::LocalPositionControlResponse>
{
  static const char* value()
  {
    return DataType< ::dji_sdk::LocalPositionControl >::value();
  }
  static const char* value(const ::dji_sdk::LocalPositionControlResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // DJI_SDK_MESSAGE_LOCALPOSITIONCONTROL_H
