// Generated by gencpp from file dji_sdk/MissionHpDownload.msg
// DO NOT EDIT!


#ifndef DJI_SDK_MESSAGE_MISSIONHPDOWNLOAD_H
#define DJI_SDK_MESSAGE_MISSIONHPDOWNLOAD_H

#include <ros/service_traits.h>


#include <dji_sdk/MissionHpDownloadRequest.h>
#include <dji_sdk/MissionHpDownloadResponse.h>


namespace dji_sdk
{

struct MissionHpDownload
{

typedef MissionHpDownloadRequest Request;
typedef MissionHpDownloadResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct MissionHpDownload
} // namespace dji_sdk


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::dji_sdk::MissionHpDownload > {
  static const char* value()
  {
    return "e36e66ca170c4d03ee023ad56c6bb5a0";
  }

  static const char* value(const ::dji_sdk::MissionHpDownload&) { return value(); }
};

template<>
struct DataType< ::dji_sdk::MissionHpDownload > {
  static const char* value()
  {
    return "dji_sdk/MissionHpDownload";
  }

  static const char* value(const ::dji_sdk::MissionHpDownload&) { return value(); }
};


// service_traits::MD5Sum< ::dji_sdk::MissionHpDownloadRequest> should match 
// service_traits::MD5Sum< ::dji_sdk::MissionHpDownload > 
template<>
struct MD5Sum< ::dji_sdk::MissionHpDownloadRequest>
{
  static const char* value()
  {
    return MD5Sum< ::dji_sdk::MissionHpDownload >::value();
  }
  static const char* value(const ::dji_sdk::MissionHpDownloadRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::dji_sdk::MissionHpDownloadRequest> should match 
// service_traits::DataType< ::dji_sdk::MissionHpDownload > 
template<>
struct DataType< ::dji_sdk::MissionHpDownloadRequest>
{
  static const char* value()
  {
    return DataType< ::dji_sdk::MissionHpDownload >::value();
  }
  static const char* value(const ::dji_sdk::MissionHpDownloadRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::dji_sdk::MissionHpDownloadResponse> should match 
// service_traits::MD5Sum< ::dji_sdk::MissionHpDownload > 
template<>
struct MD5Sum< ::dji_sdk::MissionHpDownloadResponse>
{
  static const char* value()
  {
    return MD5Sum< ::dji_sdk::MissionHpDownload >::value();
  }
  static const char* value(const ::dji_sdk::MissionHpDownloadResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::dji_sdk::MissionHpDownloadResponse> should match 
// service_traits::DataType< ::dji_sdk::MissionHpDownload > 
template<>
struct DataType< ::dji_sdk::MissionHpDownloadResponse>
{
  static const char* value()
  {
    return DataType< ::dji_sdk::MissionHpDownload >::value();
  }
  static const char* value(const ::dji_sdk::MissionHpDownloadResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // DJI_SDK_MESSAGE_MISSIONHPDOWNLOAD_H
