// Generated by gencpp from file dji_sdk/MissionFmSetTarget.msg
// DO NOT EDIT!


#ifndef DJI_SDK_MESSAGE_MISSIONFMSETTARGET_H
#define DJI_SDK_MESSAGE_MISSIONFMSETTARGET_H

#include <ros/service_traits.h>


#include <dji_sdk/MissionFmSetTargetRequest.h>
#include <dji_sdk/MissionFmSetTargetResponse.h>


namespace dji_sdk
{

struct MissionFmSetTarget
{

typedef MissionFmSetTargetRequest Request;
typedef MissionFmSetTargetResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct MissionFmSetTarget
} // namespace dji_sdk


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::dji_sdk::MissionFmSetTarget > {
  static const char* value()
  {
    return "9ee16cc78eb2fc59f786dcdc9263f07f";
  }

  static const char* value(const ::dji_sdk::MissionFmSetTarget&) { return value(); }
};

template<>
struct DataType< ::dji_sdk::MissionFmSetTarget > {
  static const char* value()
  {
    return "dji_sdk/MissionFmSetTarget";
  }

  static const char* value(const ::dji_sdk::MissionFmSetTarget&) { return value(); }
};


// service_traits::MD5Sum< ::dji_sdk::MissionFmSetTargetRequest> should match 
// service_traits::MD5Sum< ::dji_sdk::MissionFmSetTarget > 
template<>
struct MD5Sum< ::dji_sdk::MissionFmSetTargetRequest>
{
  static const char* value()
  {
    return MD5Sum< ::dji_sdk::MissionFmSetTarget >::value();
  }
  static const char* value(const ::dji_sdk::MissionFmSetTargetRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::dji_sdk::MissionFmSetTargetRequest> should match 
// service_traits::DataType< ::dji_sdk::MissionFmSetTarget > 
template<>
struct DataType< ::dji_sdk::MissionFmSetTargetRequest>
{
  static const char* value()
  {
    return DataType< ::dji_sdk::MissionFmSetTarget >::value();
  }
  static const char* value(const ::dji_sdk::MissionFmSetTargetRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::dji_sdk::MissionFmSetTargetResponse> should match 
// service_traits::MD5Sum< ::dji_sdk::MissionFmSetTarget > 
template<>
struct MD5Sum< ::dji_sdk::MissionFmSetTargetResponse>
{
  static const char* value()
  {
    return MD5Sum< ::dji_sdk::MissionFmSetTarget >::value();
  }
  static const char* value(const ::dji_sdk::MissionFmSetTargetResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::dji_sdk::MissionFmSetTargetResponse> should match 
// service_traits::DataType< ::dji_sdk::MissionFmSetTarget > 
template<>
struct DataType< ::dji_sdk::MissionFmSetTargetResponse>
{
  static const char* value()
  {
    return DataType< ::dji_sdk::MissionFmSetTarget >::value();
  }
  static const char* value(const ::dji_sdk::MissionFmSetTargetResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // DJI_SDK_MESSAGE_MISSIONFMSETTARGET_H
