// Generated by gencpp from file dji_sdk/MissionWpDownload.msg
// DO NOT EDIT!


#ifndef DJI_SDK_MESSAGE_MISSIONWPDOWNLOAD_H
#define DJI_SDK_MESSAGE_MISSIONWPDOWNLOAD_H

#include <ros/service_traits.h>


#include <dji_sdk/MissionWpDownloadRequest.h>
#include <dji_sdk/MissionWpDownloadResponse.h>


namespace dji_sdk
{

struct MissionWpDownload
{

typedef MissionWpDownloadRequest Request;
typedef MissionWpDownloadResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct MissionWpDownload
} // namespace dji_sdk


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::dji_sdk::MissionWpDownload > {
  static const char* value()
  {
    return "7c965e82a72d204e1e6d1e75389efb89";
  }

  static const char* value(const ::dji_sdk::MissionWpDownload&) { return value(); }
};

template<>
struct DataType< ::dji_sdk::MissionWpDownload > {
  static const char* value()
  {
    return "dji_sdk/MissionWpDownload";
  }

  static const char* value(const ::dji_sdk::MissionWpDownload&) { return value(); }
};


// service_traits::MD5Sum< ::dji_sdk::MissionWpDownloadRequest> should match 
// service_traits::MD5Sum< ::dji_sdk::MissionWpDownload > 
template<>
struct MD5Sum< ::dji_sdk::MissionWpDownloadRequest>
{
  static const char* value()
  {
    return MD5Sum< ::dji_sdk::MissionWpDownload >::value();
  }
  static const char* value(const ::dji_sdk::MissionWpDownloadRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::dji_sdk::MissionWpDownloadRequest> should match 
// service_traits::DataType< ::dji_sdk::MissionWpDownload > 
template<>
struct DataType< ::dji_sdk::MissionWpDownloadRequest>
{
  static const char* value()
  {
    return DataType< ::dji_sdk::MissionWpDownload >::value();
  }
  static const char* value(const ::dji_sdk::MissionWpDownloadRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::dji_sdk::MissionWpDownloadResponse> should match 
// service_traits::MD5Sum< ::dji_sdk::MissionWpDownload > 
template<>
struct MD5Sum< ::dji_sdk::MissionWpDownloadResponse>
{
  static const char* value()
  {
    return MD5Sum< ::dji_sdk::MissionWpDownload >::value();
  }
  static const char* value(const ::dji_sdk::MissionWpDownloadResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::dji_sdk::MissionWpDownloadResponse> should match 
// service_traits::DataType< ::dji_sdk::MissionWpDownload > 
template<>
struct DataType< ::dji_sdk::MissionWpDownloadResponse>
{
  static const char* value()
  {
    return DataType< ::dji_sdk::MissionWpDownload >::value();
  }
  static const char* value(const ::dji_sdk::MissionWpDownloadResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // DJI_SDK_MESSAGE_MISSIONWPDOWNLOAD_H
