// Generated by gencpp from file dji_sdk/SDKPermissionControl.msg
// DO NOT EDIT!


#ifndef DJI_SDK_MESSAGE_SDKPERMISSIONCONTROL_H
#define DJI_SDK_MESSAGE_SDKPERMISSIONCONTROL_H

#include <ros/service_traits.h>


#include <dji_sdk/SDKPermissionControlRequest.h>
#include <dji_sdk/SDKPermissionControlResponse.h>


namespace dji_sdk
{

struct SDKPermissionControl
{

typedef SDKPermissionControlRequest Request;
typedef SDKPermissionControlResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct SDKPermissionControl
} // namespace dji_sdk


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::dji_sdk::SDKPermissionControl > {
  static const char* value()
  {
    return "de4f6d2b1e0b995a7d472739c6318805";
  }

  static const char* value(const ::dji_sdk::SDKPermissionControl&) { return value(); }
};

template<>
struct DataType< ::dji_sdk::SDKPermissionControl > {
  static const char* value()
  {
    return "dji_sdk/SDKPermissionControl";
  }

  static const char* value(const ::dji_sdk::SDKPermissionControl&) { return value(); }
};


// service_traits::MD5Sum< ::dji_sdk::SDKPermissionControlRequest> should match 
// service_traits::MD5Sum< ::dji_sdk::SDKPermissionControl > 
template<>
struct MD5Sum< ::dji_sdk::SDKPermissionControlRequest>
{
  static const char* value()
  {
    return MD5Sum< ::dji_sdk::SDKPermissionControl >::value();
  }
  static const char* value(const ::dji_sdk::SDKPermissionControlRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::dji_sdk::SDKPermissionControlRequest> should match 
// service_traits::DataType< ::dji_sdk::SDKPermissionControl > 
template<>
struct DataType< ::dji_sdk::SDKPermissionControlRequest>
{
  static const char* value()
  {
    return DataType< ::dji_sdk::SDKPermissionControl >::value();
  }
  static const char* value(const ::dji_sdk::SDKPermissionControlRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::dji_sdk::SDKPermissionControlResponse> should match 
// service_traits::MD5Sum< ::dji_sdk::SDKPermissionControl > 
template<>
struct MD5Sum< ::dji_sdk::SDKPermissionControlResponse>
{
  static const char* value()
  {
    return MD5Sum< ::dji_sdk::SDKPermissionControl >::value();
  }
  static const char* value(const ::dji_sdk::SDKPermissionControlResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::dji_sdk::SDKPermissionControlResponse> should match 
// service_traits::DataType< ::dji_sdk::SDKPermissionControl > 
template<>
struct DataType< ::dji_sdk::SDKPermissionControlResponse>
{
  static const char* value()
  {
    return DataType< ::dji_sdk::SDKPermissionControl >::value();
  }
  static const char* value(const ::dji_sdk::SDKPermissionControlResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // DJI_SDK_MESSAGE_SDKPERMISSIONCONTROL_H
