// Generated by gencpp from file dji_sdk/SendDataToRemoteDevice.msg
// DO NOT EDIT!


#ifndef DJI_SDK_MESSAGE_SENDDATATOREMOTEDEVICE_H
#define DJI_SDK_MESSAGE_SENDDATATOREMOTEDEVICE_H

#include <ros/service_traits.h>


#include <dji_sdk/SendDataToRemoteDeviceRequest.h>
#include <dji_sdk/SendDataToRemoteDeviceResponse.h>


namespace dji_sdk
{

struct SendDataToRemoteDevice
{

typedef SendDataToRemoteDeviceRequest Request;
typedef SendDataToRemoteDeviceResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct SendDataToRemoteDevice
} // namespace dji_sdk


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::dji_sdk::SendDataToRemoteDevice > {
  static const char* value()
  {
    return "bd93c41175d536c2f80ba6dced2e859b";
  }

  static const char* value(const ::dji_sdk::SendDataToRemoteDevice&) { return value(); }
};

template<>
struct DataType< ::dji_sdk::SendDataToRemoteDevice > {
  static const char* value()
  {
    return "dji_sdk/SendDataToRemoteDevice";
  }

  static const char* value(const ::dji_sdk::SendDataToRemoteDevice&) { return value(); }
};


// service_traits::MD5Sum< ::dji_sdk::SendDataToRemoteDeviceRequest> should match 
// service_traits::MD5Sum< ::dji_sdk::SendDataToRemoteDevice > 
template<>
struct MD5Sum< ::dji_sdk::SendDataToRemoteDeviceRequest>
{
  static const char* value()
  {
    return MD5Sum< ::dji_sdk::SendDataToRemoteDevice >::value();
  }
  static const char* value(const ::dji_sdk::SendDataToRemoteDeviceRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::dji_sdk::SendDataToRemoteDeviceRequest> should match 
// service_traits::DataType< ::dji_sdk::SendDataToRemoteDevice > 
template<>
struct DataType< ::dji_sdk::SendDataToRemoteDeviceRequest>
{
  static const char* value()
  {
    return DataType< ::dji_sdk::SendDataToRemoteDevice >::value();
  }
  static const char* value(const ::dji_sdk::SendDataToRemoteDeviceRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::dji_sdk::SendDataToRemoteDeviceResponse> should match 
// service_traits::MD5Sum< ::dji_sdk::SendDataToRemoteDevice > 
template<>
struct MD5Sum< ::dji_sdk::SendDataToRemoteDeviceResponse>
{
  static const char* value()
  {
    return MD5Sum< ::dji_sdk::SendDataToRemoteDevice >::value();
  }
  static const char* value(const ::dji_sdk::SendDataToRemoteDeviceResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::dji_sdk::SendDataToRemoteDeviceResponse> should match 
// service_traits::DataType< ::dji_sdk::SendDataToRemoteDevice > 
template<>
struct DataType< ::dji_sdk::SendDataToRemoteDeviceResponse>
{
  static const char* value()
  {
    return DataType< ::dji_sdk::SendDataToRemoteDevice >::value();
  }
  static const char* value(const ::dji_sdk::SendDataToRemoteDeviceResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // DJI_SDK_MESSAGE_SENDDATATOREMOTEDEVICE_H
