// Generated by gencpp from file dji_sdk/SyncFlagControl.msg
// DO NOT EDIT!


#ifndef DJI_SDK_MESSAGE_SYNCFLAGCONTROL_H
#define DJI_SDK_MESSAGE_SYNCFLAGCONTROL_H

#include <ros/service_traits.h>


#include <dji_sdk/SyncFlagControlRequest.h>
#include <dji_sdk/SyncFlagControlResponse.h>


namespace dji_sdk
{

struct SyncFlagControl
{

typedef SyncFlagControlRequest Request;
typedef SyncFlagControlResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct SyncFlagControl
} // namespace dji_sdk


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::dji_sdk::SyncFlagControl > {
  static const char* value()
  {
    return "848e0c067edd66153227f7c9aad5132b";
  }

  static const char* value(const ::dji_sdk::SyncFlagControl&) { return value(); }
};

template<>
struct DataType< ::dji_sdk::SyncFlagControl > {
  static const char* value()
  {
    return "dji_sdk/SyncFlagControl";
  }

  static const char* value(const ::dji_sdk::SyncFlagControl&) { return value(); }
};


// service_traits::MD5Sum< ::dji_sdk::SyncFlagControlRequest> should match 
// service_traits::MD5Sum< ::dji_sdk::SyncFlagControl > 
template<>
struct MD5Sum< ::dji_sdk::SyncFlagControlRequest>
{
  static const char* value()
  {
    return MD5Sum< ::dji_sdk::SyncFlagControl >::value();
  }
  static const char* value(const ::dji_sdk::SyncFlagControlRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::dji_sdk::SyncFlagControlRequest> should match 
// service_traits::DataType< ::dji_sdk::SyncFlagControl > 
template<>
struct DataType< ::dji_sdk::SyncFlagControlRequest>
{
  static const char* value()
  {
    return DataType< ::dji_sdk::SyncFlagControl >::value();
  }
  static const char* value(const ::dji_sdk::SyncFlagControlRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::dji_sdk::SyncFlagControlResponse> should match 
// service_traits::MD5Sum< ::dji_sdk::SyncFlagControl > 
template<>
struct MD5Sum< ::dji_sdk::SyncFlagControlResponse>
{
  static const char* value()
  {
    return MD5Sum< ::dji_sdk::SyncFlagControl >::value();
  }
  static const char* value(const ::dji_sdk::SyncFlagControlResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::dji_sdk::SyncFlagControlResponse> should match 
// service_traits::DataType< ::dji_sdk::SyncFlagControl > 
template<>
struct DataType< ::dji_sdk::SyncFlagControlResponse>
{
  static const char* value()
  {
    return DataType< ::dji_sdk::SyncFlagControl >::value();
  }
  static const char* value(const ::dji_sdk::SyncFlagControlResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // DJI_SDK_MESSAGE_SYNCFLAGCONTROL_H
