(cl:in-package dji_sdk-msg)
(cl:export '(LATITUDE_PROGRESS-VAL
          LATITUDE_PROGRESS
          LONGITUDE_PROGRESS-VAL
          LONGITUDE_PROGRESS
          ALTITUDE_PROGRESS-VAL
          ALTITUDE_PROGRESS
          INDEX_PROGRESS-VAL
          INDEX_PROGRESS
))